Still need to sleep for 2 seconds to avoid error
We get the following error on Jenkins:

Error: Future resolved more than once
    at Object.Future.return (/mnt/jenkins/workspace/End-to-End Meteor Platform Tests/meteor/dev_bundle/lib/node_modules/fibers/future.js:154:10)
    at Interface.<anonymous> (/mnt/jenkins/workspace/End-to-End Meteor Platform Tests/meteor/tools/console.js:889:18)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface.<anonymous> (readline.js:322:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:321:11)
    at Socket.ondata (readline.js:91:10)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at Pipe.onread (net.js:528:21)